<?php
return [
  [
    'title' => '空间及硬件管理',
    'icon' => 'aicon ai-shezhi',
    'module' => 'space',
    'url' => 'space',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 10,
    'childs' => [
      [
        'title' => '空间场地配置',
        'icon' => 'typcn typcn-th-menu-outline',
        'module' => 'space',
        'url' => 'space/site',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '楼宇管理',
            'icon' => '',
            'module' => 'space',
            'url' => 'space/ban/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '楼层管理',
            'icon' => '',
            'module' => 'space',
            'url' => 'space/floor/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '工位区管理',
            'icon' => '',
            'module' => 'space',
            'url' => 'space/site/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '会议室管理',
            'icon' => '',
            'module' => 'space',
            'url' => 'space/meeting/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '停车场管理',
            'icon' => '',
            'module' => 'space',
            'url' => 'space/park/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '其他场地管理',
            'icon' => '',
            'module' => 'space',
            'url' => 'space/rest/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
