<?php
return [
  [
    'title' => '在线服务',
    'icon' => 'aicon ai-shezhi',
    'module' => 'serve',
    'url' => 'serve',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '空间状态',
        'icon' => 'typcn typcn-film',
        'module' => 'serve',
        'url' => 'serve/space',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '会议室状态',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/meeting/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '工位状态',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/site/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '其他场地状态',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/rest/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '通知公告',
        'icon' => 'typcn typcn-lightbulb',
        'module' => 'serve',
        'url' => 'serve/notice',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '通知管理',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/affiche/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加通知',
                'icon' => '',
                'module' => 'serve',
                'url' => 'serve/affiche/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑通知',
                'icon' => '',
                'module' => 'serve',
                'url' => 'serve/affiche/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '公告管理',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/notice/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加公告',
                'icon' => '',
                'module' => 'serve',
                'url' => 'serve/notice/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑公告',
                'icon' => '',
                'module' => 'serve',
                'url' => 'serve/notice/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '运营管理',
        'icon' => 'fa fa-medium',
        'module' => 'serve',
        'url' => 'serve/operate',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '报事报修',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/repaire/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '空间活动管理',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/space/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '访客信息管理',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/visitors/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '信息统计',
        'icon' => 'typcn typcn-chart-line-outline',
        'module' => 'serve',
        'url' => 'serve/statistics',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '打印统计',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/printout/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '水电气使用统计',
            'icon' => '',
            'module' => 'serve',
            'url' => 'serve/electric/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
