<?php
return [
  [
    'title' => '项目管理',
    'icon' => 'aicon ai-shezhi',
    'module' => 'project',
    'url' => 'project',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '入驻管理',
        'icon' => 'fa fa-building-o',
        'module' => 'project',
        'url' => 'project/shack',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '入驻办理',
            'icon' => '',
            'module' => 'project',
            'url' => 'project/shack/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '企业管理',
            'icon' => '',
            'module' => 'project',
            'url' => 'project/firm/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '人员管理',
            'icon' => '',
            'module' => 'project',
            'url' => 'project/staff/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
