<?php
return [
  [
    'title' => '系统管理',
    'icon' => '',
    'module' => 'system',
    'url' => 'system/system',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 1,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '工作人员管理',
        'icon' => 'aicon ai-huiyuanliebiao',
        'module' => 'system',
        'url' => 'system/system',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 1,
        'childs' => [
          [
            'title' => '工作人员账号',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 5,
            'childs' => [
              [
                'title' => '添加管理员',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/adduser',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '修改管理员',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/edituser',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '删除管理员',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/deluser',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 3,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 4,
              ],
            ],
          ],
          [
            'title' => '管理员角色',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/role',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 6,
            'childs' => [
              [
                'title' => '添加角色',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/addrole',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '修改角色',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/editrole',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '删除角色',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/delrole',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 3,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/user/statusRole',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 4,
              ],
            ],
          ],
          [
            'title' => '附件管理',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/annex/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 8,
            'childs' => [
              [
                'title' => '附件上传',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/annex/upload',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '删除附件',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/annex/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '收藏夹图标上传',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/annex/favicon',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 3,
              ],
            ],
          ],
          [
            'title' => '语言包管理',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/language/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 9,
            'childs' => [
              [
                'title' => '添加语言包',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/language/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
              [
                'title' => '修改语言包',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/language/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
              [
                'title' => '删除语言包',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/language/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/language/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/language/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '开发者',
        'icon' => 'aicon ai-shezhi',
        'module' => 'system',
        'url' => 'system/extend',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 3,
        'childs' => [
          [
            'title' => '数据库设计',
            'icon' => 'aicon ai-shujukuguanli',
            'module' => 'system',
            'url' => 'system/design/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '数据表导出',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/design/export',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '数据表结构导出',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/design/exportStruct',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '系统设置',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/system/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
            'childs' => [
              [
                'title' => '基础配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/system/index',
                'param' => 'group=base',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '系统配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/system/index',
                'param' => 'group=sys',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '上传配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/system/index',
                'param' => 'group=upload',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 3,
              ],
              [
                'title' => '开发配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/system/index',
                'param' => 'group=develop',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 4,
              ],
              [
                'title' => '数据库配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/system/index',
                'param' => 'group=databases',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 5,
              ],
            ],
          ],
          [
            'title' => '本地模块',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/module/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
            'childs' => [
              [
                'title' => '安装模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/install',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '卸载模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/uninstall',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 3,
              ],
              [
                'title' => '设置默认模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/setdefault',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 4,
              ],
              [
                'title' => '删除模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 5,
              ],
              [
                'title' => '生成模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/design',
                'param' => '',
                'target' => '_self',
                'debug' => 1,
                'system' => 1,
                'nav' => 1,
                'sort' => 6,
              ],
              [
                'title' => '模块打包',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/package',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 7,
              ],
              [
                'title' => '主题管理',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/theme',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 8,
              ],
              [
                'title' => '设置默认主题',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/setdefaulttheme',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 9,
              ],
              [
                'title' => '导入主题SQL',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/exeSql',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 10,
              ],
              [
                'title' => '删除主题',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/deltheme',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 10,
              ],
              [
                'title' => '导入模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/import',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 11,
              ],
              [
                'title' => '编辑模块',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
              [
                'title' => '模块图标上传',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/module/icon',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
            ],
          ],
          [
            'title' => '配置管理',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/config/index',
            'param' => '',
            'target' => '_self',
            'debug' => 1,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
            'childs' => [
              [
                'title' => '添加配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/config/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '修改配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/config/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '删除配置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/config/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 3,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/config/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 4,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/config/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 5,
              ],
            ],
          ],
          [
            'title' => '系统菜单',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/menu/index',
            'param' => '',
            'target' => '_self',
            'debug' => 1,
            'system' => 1,
            'nav' => 1,
            'sort' => 3,
            'childs' => [
              [
                'title' => '添加菜单',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 1,
              ],
              [
                'title' => '修改菜单',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 2,
              ],
              [
                'title' => '删除菜单',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 3,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 4,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 5,
              ],
              [
                'title' => '添加快捷菜单',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/quick',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 6,
              ],
              [
                'title' => '导出菜单',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/menu/export',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 7,
              ],
            ],
          ],
          [
            'title' => '数据库管理',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/database/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 6,
            'childs' => [
              [
                'title' => '备份数据库',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/database/export',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '恢复数据库',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/database/import',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '优化数据库',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/database/optimize',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '删除备份',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/database/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '修复数据库',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/database/repair',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '系统日志',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/log/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 7,
            'childs' => [
              [
                'title' => '删除日志',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/log/del',
                'param' => 'table=admin_log',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
              [
                'title' => '清空日志',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/log/clear',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 0,
                'sort' => 100,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
